"""Migração Inicial

Revision ID: 8bc1166564d5
Revises: 
Create Date: 2024-11-18 14:09:42.525821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc1166564d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('id_medico', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('medico',
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('especialidade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_medico')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medico')
    op.drop_table('paciente')
    # ### end Alembic commands ###
